###############################################################################
# @generated
# DO NOT MODIFY: This file is auto-generated by a crate_universe tool. To
# regenerate this file, run the following:
#
#     bazel run //vendor:crates_vendor
###############################################################################
"""
# `crates_repository` API

- [aliases](#aliases)
- [crate_deps](#crate_deps)
- [all_crate_deps](#all_crate_deps)
- [crate_repositories](#crate_repositories)

"""

load("@bazel_skylib//lib:selects.bzl", "selects")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

###############################################################################
# MACROS API
###############################################################################

# An identifier that represent common dependencies (unconditional).
_COMMON_CONDITION = ""

def _flatten_dependency_maps(all_dependency_maps):
    """Flatten a list of dependency maps into one dictionary.

    Dependency maps have the following structure:

    ```python
    DEPENDENCIES_MAP = {
        # The first key in the map is a Bazel package
        # name of the workspace this file is defined in.
        "workspace_member_package": {

            # Not all dependnecies are supported for all platforms.
            # the condition key is the condition required to be true
            # on the host platform.
            "condition": {

                # An alias to a crate target.     # The label of the crate target the
                # Aliases are only crate names.   # package name refers to.
                "package_name":                   "@full//:label",
            }
        }
    }
    ```

    Args:
        all_dependency_maps (list): A list of dicts as described above

    Returns:
        dict: A dictionary as described above
    """
    dependencies = {}

    for workspace_deps_map in all_dependency_maps:
        for pkg_name, conditional_deps_map in workspace_deps_map.items():
            if pkg_name not in dependencies:
                non_frozen_map = dict()
                for key, values in conditional_deps_map.items():
                    non_frozen_map.update({key: dict(values.items())})
                dependencies.setdefault(pkg_name, non_frozen_map)
                continue

            for condition, deps_map in conditional_deps_map.items():
                # If the condition has not been recorded, do so and continue
                if condition not in dependencies[pkg_name]:
                    dependencies[pkg_name].setdefault(condition, dict(deps_map.items()))
                    continue

                # Alert on any miss-matched dependencies
                inconsistent_entries = []
                for crate_name, crate_label in deps_map.items():
                    existing = dependencies[pkg_name][condition].get(crate_name)
                    if existing and existing != crate_label:
                        inconsistent_entries.append((crate_name, existing, crate_label))
                    dependencies[pkg_name][condition].update({crate_name: crate_label})

    return dependencies

def crate_deps(deps, package_name = None):
    """Finds the fully qualified label of the requested crates for the package where this macro is called.

    Args:
        deps (list): The desired list of crate targets.
        package_name (str, optional): The package name of the set of dependencies to look up.
            Defaults to `native.package_name()`.

    Returns:
        list: A list of labels to generated rust targets (str)
    """

    if not deps:
        return []

    if package_name == None:
        package_name = native.package_name()

    # Join both sets of dependencies
    dependencies = _flatten_dependency_maps([
        _NORMAL_DEPENDENCIES,
        _NORMAL_DEV_DEPENDENCIES,
        _PROC_MACRO_DEPENDENCIES,
        _PROC_MACRO_DEV_DEPENDENCIES,
        _BUILD_DEPENDENCIES,
        _BUILD_PROC_MACRO_DEPENDENCIES,
    ]).pop(package_name, {})

    # Combine all conditional packages so we can easily index over a flat list
    # TODO: Perhaps this should actually return select statements and maintain
    # the conditionals of the dependencies
    flat_deps = {}
    for deps_set in dependencies.values():
        for crate_name, crate_label in deps_set.items():
            flat_deps.update({crate_name: crate_label})

    missing_crates = []
    crate_targets = []
    for crate_target in deps:
        if crate_target not in flat_deps:
            missing_crates.append(crate_target)
        else:
            crate_targets.append(flat_deps[crate_target])

    if missing_crates:
        fail("Could not find crates `{}` among dependencies of `{}`. Available dependencies were `{}`".format(
            missing_crates,
            package_name,
            dependencies,
        ))

    return crate_targets

def all_crate_deps(
        normal = False,
        normal_dev = False,
        proc_macro = False,
        proc_macro_dev = False,
        build = False,
        build_proc_macro = False,
        package_name = None):
    """Finds the fully qualified label of all requested direct crate dependencies \
    for the package where this macro is called.

    If no parameters are set, all normal dependencies are returned. Setting any one flag will
    otherwise impact the contents of the returned list.

    Args:
        normal (bool, optional): If True, normal dependencies are included in the
            output list.
        normal_dev (bool, optional): If True, normla dev dependencies will be
            included in the output list..
        proc_macro (bool, optional): If True, proc_macro dependencies are included
            in the output list.
        proc_macro_dev (bool, optional): If True, dev proc_macro dependencies are
            included in the output list.
        build (bool, optional): If True, build dependencies are included
            in the output list.
        build_proc_macro (bool, optional): If True, build proc_macro dependencies are
            included in the output list.
        package_name (str, optional): The package name of the set of dependencies to look up.
            Defaults to `native.package_name()` when unset.

    Returns:
        list: A list of labels to generated rust targets (str)
    """

    if package_name == None:
        package_name = native.package_name()

    # Determine the relevant maps to use
    all_dependency_maps = []
    if normal:
        all_dependency_maps.append(_NORMAL_DEPENDENCIES)
    if normal_dev:
        all_dependency_maps.append(_NORMAL_DEV_DEPENDENCIES)
    if proc_macro:
        all_dependency_maps.append(_PROC_MACRO_DEPENDENCIES)
    if proc_macro_dev:
        all_dependency_maps.append(_PROC_MACRO_DEV_DEPENDENCIES)
    if build:
        all_dependency_maps.append(_BUILD_DEPENDENCIES)
    if build_proc_macro:
        all_dependency_maps.append(_BUILD_PROC_MACRO_DEPENDENCIES)

    # Default to always using normal dependencies
    if not all_dependency_maps:
        all_dependency_maps.append(_NORMAL_DEPENDENCIES)

    dependencies = _flatten_dependency_maps(all_dependency_maps).pop(package_name, None)

    if not dependencies:
        if dependencies == None:
            fail("Tried to get all_crate_deps for package " + package_name + " but that package had no Cargo.toml file")
        else:
            return []

    crate_deps = list(dependencies.pop(_COMMON_CONDITION, {}).values())
    for condition, deps in dependencies.items():
        crate_deps += selects.with_or({_CONDITIONS[condition]: deps.values()})

    return crate_deps

def aliases(
        normal = False,
        normal_dev = False,
        proc_macro = False,
        proc_macro_dev = False,
        build = False,
        build_proc_macro = False,
        package_name = None):
    """Produces a map of Crate alias names to their original label

    If no dependency kinds are specified, `normal` and `proc_macro` are used by default.
    Setting any one flag will otherwise determine the contents of the returned dict.

    Args:
        normal (bool, optional): If True, normal dependencies are included in the
            output list.
        normal_dev (bool, optional): If True, normla dev dependencies will be
            included in the output list..
        proc_macro (bool, optional): If True, proc_macro dependencies are included
            in the output list.
        proc_macro_dev (bool, optional): If True, dev proc_macro dependencies are
            included in the output list.
        build (bool, optional): If True, build dependencies are included
            in the output list.
        build_proc_macro (bool, optional): If True, build proc_macro dependencies are
            included in the output list.
        package_name (str, optional): The package name of the set of dependencies to look up.
            Defaults to `native.package_name()` when unset.

    Returns:
        dict: The aliases of all associated packages
    """
    if package_name == None:
        package_name = native.package_name()

    # Determine the relevant maps to use
    all_aliases_maps = []
    if normal:
        all_aliases_maps.append(_NORMAL_ALIASES)
    if normal_dev:
        all_aliases_maps.append(_NORMAL_DEV_ALIASES)
    if proc_macro:
        all_aliases_maps.append(_PROC_MACRO_ALIASES)
    if proc_macro_dev:
        all_aliases_maps.append(_PROC_MACRO_DEV_ALIASES)
    if build:
        all_aliases_maps.append(_BUILD_ALIASES)
    if build_proc_macro:
        all_aliases_maps.append(_BUILD_PROC_MACRO_ALIASES)

    # Default to always using normal aliases
    if not all_aliases_maps:
        all_aliases_maps.append(_NORMAL_ALIASES)
        all_aliases_maps.append(_PROC_MACRO_ALIASES)

    aliases = _flatten_dependency_maps(all_aliases_maps).pop(package_name, None)

    if not aliases:
        return dict()

    common_items = aliases.pop(_COMMON_CONDITION, {}).items()

    # If there are only common items in the dictionary, immediately return them
    if not len(aliases.keys()) == 1:
        return dict(common_items)

    # Build a single select statement where each conditional has accounted for the
    # common set of aliases.
    crate_aliases = {"//conditions:default": common_items}
    for condition, deps in aliases.items():
        condition_triples = _CONDITIONS[condition]
        if condition_triples in crate_aliases:
            crate_aliases[condition_triples].update(deps)
        else:
            crate_aliases.update({_CONDITIONS[condition]: dict(deps.items() + common_items)})

    return selects.with_or(crate_aliases)

###############################################################################
# WORKSPACE MEMBER DEPS AND ALIASES
###############################################################################

_NORMAL_DEPENDENCIES = {
    "": {
        _COMMON_CONDITION: {
            "prost": "@crates_vendor__prost-0.11.0//:prost",
            "serde": "@crates_vendor__serde-1.0.143//:serde",
            "serde_yaml": "@crates_vendor__serde_yaml-0.9.9//:serde_yaml",
            "structopt": "@crates_vendor__structopt-0.3.26//:structopt",
            "tokio": "@crates_vendor__tokio-1.20.1//:tokio",
            "tonic": "@crates_vendor__tonic-0.8.0//:tonic",
        },
    },
}

_NORMAL_ALIASES = {
    "": {
        _COMMON_CONDITION: {
        },
    },
}

_NORMAL_DEV_DEPENDENCIES = {
    "": {
        _COMMON_CONDITION: {
            "assert_cmd": "@crates_vendor__assert_cmd-2.0.4//:assert_cmd",
            "futures-util": "@crates_vendor__futures-util-0.3.23//:futures_util",
            "predicates": "@crates_vendor__predicates-2.1.1//:predicates",
            "tokio-stream": "@crates_vendor__tokio-stream-0.1.9//:tokio_stream",
            "tonic-health": "@crates_vendor__tonic-health-0.7.0//:tonic_health",
        },
    },
}

_NORMAL_DEV_ALIASES = {
    "": {
        _COMMON_CONDITION: {
        },
    },
}

_PROC_MACRO_DEPENDENCIES = {
    "": {
    },
}

_PROC_MACRO_ALIASES = {
    "": {
    },
}

_PROC_MACRO_DEV_DEPENDENCIES = {
    "": {
    },
}

_PROC_MACRO_DEV_ALIASES = {
    "": {
        _COMMON_CONDITION: {
        },
    },
}

_BUILD_DEPENDENCIES = {
    "": {
        _COMMON_CONDITION: {
            "tonic-build": "@crates_vendor__tonic-build-0.8.0//:tonic_build",
        },
    },
}

_BUILD_ALIASES = {
    "": {
        _COMMON_CONDITION: {
        },
    },
}

_BUILD_PROC_MACRO_DEPENDENCIES = {
    "": {
    },
}

_BUILD_PROC_MACRO_ALIASES = {
    "": {
    },
}

_CONDITIONS = {
    "aarch64-pc-windows-msvc": [],
    "aarch64-uwp-windows-msvc": [],
    "cfg(all(any(target_arch = \"x86_64\", target_arch = \"aarch64\"), target_os = \"hermit\"))": [],
    "cfg(all(target_arch = \"wasm32\", target_vendor = \"unknown\", target_os = \"unknown\", target_env = \"\"))": ["wasm32-unknown-unknown"],
    "cfg(any(target_arch = \"x86\", target_arch = \"x86_64\", all(any(target_arch = \"aarch64\", target_arch = \"arm\"), any(target_os = \"android\", target_os = \"fuchsia\", target_os = \"linux\"))))": ["aarch64-linux-android", "aarch64-unknown-linux-gnu", "arm-unknown-linux-gnueabi", "armv7-linux-androideabi", "armv7-unknown-linux-gnueabi", "i686-apple-darwin", "i686-linux-android", "i686-pc-windows-msvc", "i686-unknown-freebsd", "i686-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-apple-ios", "x86_64-linux-android", "x86_64-pc-windows-msvc", "x86_64-unknown-freebsd", "x86_64-unknown-linux-gnu"],
    "cfg(any(target_os = \"android\", target_os = \"linux\"))": ["aarch64-linux-android", "aarch64-unknown-linux-gnu", "arm-unknown-linux-gnueabi", "armv7-linux-androideabi", "armv7-unknown-linux-gnueabi", "i686-linux-android", "i686-unknown-linux-gnu", "powerpc-unknown-linux-gnu", "s390x-unknown-linux-gnu", "x86_64-linux-android", "x86_64-unknown-linux-gnu"],
    "cfg(any(target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"illumos\", target_os = \"netbsd\", target_os = \"openbsd\", target_os = \"solaris\"))": ["i686-unknown-freebsd", "x86_64-unknown-freebsd"],
    "cfg(any(unix, target_os = \"wasi\"))": ["aarch64-apple-darwin", "aarch64-apple-ios", "aarch64-apple-ios-sim", "aarch64-linux-android", "aarch64-unknown-linux-gnu", "arm-unknown-linux-gnueabi", "armv7-linux-androideabi", "armv7-unknown-linux-gnueabi", "i686-apple-darwin", "i686-linux-android", "i686-unknown-freebsd", "i686-unknown-linux-gnu", "powerpc-unknown-linux-gnu", "s390x-unknown-linux-gnu", "wasm32-wasi", "x86_64-apple-darwin", "x86_64-apple-ios", "x86_64-linux-android", "x86_64-unknown-freebsd", "x86_64-unknown-linux-gnu"],
    "cfg(not(windows))": ["aarch64-apple-darwin", "aarch64-apple-ios", "aarch64-apple-ios-sim", "aarch64-linux-android", "aarch64-unknown-linux-gnu", "arm-unknown-linux-gnueabi", "armv7-linux-androideabi", "armv7-unknown-linux-gnueabi", "i686-apple-darwin", "i686-linux-android", "i686-unknown-freebsd", "i686-unknown-linux-gnu", "powerpc-unknown-linux-gnu", "riscv32imc-unknown-none-elf", "s390x-unknown-linux-gnu", "wasm32-unknown-unknown", "wasm32-wasi", "x86_64-apple-darwin", "x86_64-apple-ios", "x86_64-linux-android", "x86_64-unknown-freebsd", "x86_64-unknown-linux-gnu"],
    "cfg(target_arch = \"wasm32\")": ["wasm32-unknown-unknown", "wasm32-wasi"],
    "cfg(target_os = \"hermit\")": [],
    "cfg(target_os = \"redox\")": [],
    "cfg(target_os = \"wasi\")": ["wasm32-wasi"],
    "cfg(target_os = \"windows\")": ["i686-pc-windows-msvc", "x86_64-pc-windows-msvc"],
    "cfg(unix)": ["aarch64-apple-darwin", "aarch64-apple-ios", "aarch64-apple-ios-sim", "aarch64-linux-android", "aarch64-unknown-linux-gnu", "arm-unknown-linux-gnueabi", "armv7-linux-androideabi", "armv7-unknown-linux-gnueabi", "i686-apple-darwin", "i686-linux-android", "i686-unknown-freebsd", "i686-unknown-linux-gnu", "powerpc-unknown-linux-gnu", "s390x-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-apple-ios", "x86_64-linux-android", "x86_64-unknown-freebsd", "x86_64-unknown-linux-gnu"],
    "cfg(windows)": ["i686-pc-windows-msvc", "x86_64-pc-windows-msvc"],
    "i686-pc-windows-gnu": [],
    "i686-pc-windows-msvc": ["i686-pc-windows-msvc"],
    "i686-uwp-windows-gnu": [],
    "i686-uwp-windows-msvc": [],
    "x86_64-pc-windows-gnu": [],
    "x86_64-pc-windows-msvc": ["x86_64-pc-windows-msvc"],
    "x86_64-uwp-windows-gnu": [],
    "x86_64-uwp-windows-msvc": [],
}

###############################################################################

def crate_repositories():
    """A macro for defining repositories for all generated crates"""
    maybe(
        http_archive,
        name = "crates_vendor__aho-corasick-0.7.18",
        sha256 = "1e37cfd5e7657ada45f742d6e99ca5788580b5c529dc78faf11ece6dc702656f",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/aho-corasick/0.7.18/download"],
        strip_prefix = "aho-corasick-0.7.18",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.aho-corasick-0.7.18.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__ansi_term-0.12.1",
        sha256 = "d52a9bb7ec0cf484c551830a7ce27bd20d67eac647e1befb56b0be4ee39a55d2",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/ansi_term/0.12.1/download"],
        strip_prefix = "ansi_term-0.12.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.ansi_term-0.12.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__anyhow-1.0.62",
        sha256 = "1485d4d2cc45e7b201ee3767015c96faa5904387c9d87c6efdd0fb511f12d305",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/anyhow/1.0.62/download"],
        strip_prefix = "anyhow-1.0.62",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.anyhow-1.0.62.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__assert_cmd-2.0.4",
        sha256 = "93ae1ddd39efd67689deb1979d80bad3bf7f2b09c6e6117c8d1f2443b5e2f83e",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/assert_cmd/2.0.4/download"],
        strip_prefix = "assert_cmd-2.0.4",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.assert_cmd-2.0.4.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__async-stream-0.3.3",
        sha256 = "dad5c83079eae9969be7fadefe640a1c566901f05ff91ab221de4b6f68d9507e",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/async-stream/0.3.3/download"],
        strip_prefix = "async-stream-0.3.3",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.async-stream-0.3.3.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__async-stream-impl-0.3.3",
        sha256 = "10f203db73a71dfa2fb6dd22763990fa26f3d2625a6da2da900d23b87d26be27",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/async-stream-impl/0.3.3/download"],
        strip_prefix = "async-stream-impl-0.3.3",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.async-stream-impl-0.3.3.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__async-trait-0.1.57",
        sha256 = "76464446b8bc32758d7e88ee1a804d9914cd9b1cb264c029899680b0be29826f",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/async-trait/0.1.57/download"],
        strip_prefix = "async-trait-0.1.57",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.async-trait-0.1.57.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__atty-0.2.14",
        sha256 = "d9b39be18770d11421cdb1b9947a45dd3f37e93092cbf377614828a319d5fee8",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/atty/0.2.14/download"],
        strip_prefix = "atty-0.2.14",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.atty-0.2.14.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__autocfg-1.1.0",
        sha256 = "d468802bab17cbc0cc575e9b053f41e72aa36bfa6b7f55e3529ffa43161b97fa",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/autocfg/1.1.0/download"],
        strip_prefix = "autocfg-1.1.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.autocfg-1.1.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__axum-0.5.15",
        sha256 = "9de18bc5f2e9df8f52da03856bf40e29b747de5a84e43aefff90e3dc4a21529b",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/axum/0.5.15/download"],
        strip_prefix = "axum-0.5.15",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.axum-0.5.15.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__axum-core-0.2.7",
        sha256 = "e4f44a0e6200e9d11a1cdc989e4b358f6e3d354fbf48478f345a17f4e43f8635",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/axum-core/0.2.7/download"],
        strip_prefix = "axum-core-0.2.7",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.axum-core-0.2.7.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__base64-0.13.0",
        sha256 = "904dfeac50f3cdaba28fc6f57fdcddb75f49ed61346676a78c4ffe55877802fd",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/base64/0.13.0/download"],
        strip_prefix = "base64-0.13.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.base64-0.13.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__bitflags-1.3.2",
        sha256 = "bef38d45163c2f1dde094a7dfd33ccf595c92905c8f8f4fdc18d06fb1037718a",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/bitflags/1.3.2/download"],
        strip_prefix = "bitflags-1.3.2",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.bitflags-1.3.2.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__bstr-0.2.17",
        sha256 = "ba3569f383e8f1598449f1a423e72e99569137b47740b1da11ef19af3d5c3223",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/bstr/0.2.17/download"],
        strip_prefix = "bstr-0.2.17",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.bstr-0.2.17.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__bumpalo-3.11.0",
        sha256 = "c1ad822118d20d2c234f427000d5acc36eabe1e29a348c89b63dd60b13f28e5d",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/bumpalo/3.11.0/download"],
        strip_prefix = "bumpalo-3.11.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.bumpalo-3.11.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__bytes-1.2.1",
        sha256 = "ec8a7b6a70fde80372154c65702f00a0f56f3e1c36abbc6c440484be248856db",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/bytes/1.2.1/download"],
        strip_prefix = "bytes-1.2.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.bytes-1.2.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__cc-1.0.73",
        sha256 = "2fff2a6927b3bb87f9595d67196a70493f627687a71d87a0d692242c33f58c11",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/cc/1.0.73/download"],
        strip_prefix = "cc-1.0.73",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.cc-1.0.73.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__cfg-if-1.0.0",
        sha256 = "baf1de4339761588bc0619e3cbc0120ee582ebb74b53b4efbf79117bd2da40fd",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/cfg-if/1.0.0/download"],
        strip_prefix = "cfg-if-1.0.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.cfg-if-1.0.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__clap-2.34.0",
        sha256 = "a0610544180c38b88101fecf2dd634b174a62eef6946f84dfc6a7127512b381c",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/clap/2.34.0/download"],
        strip_prefix = "clap-2.34.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.clap-2.34.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__difflib-0.4.0",
        sha256 = "6184e33543162437515c2e2b48714794e37845ec9851711914eec9d308f6ebe8",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/difflib/0.4.0/download"],
        strip_prefix = "difflib-0.4.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.difflib-0.4.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__doc-comment-0.3.3",
        sha256 = "fea41bba32d969b513997752735605054bc0dfa92b4c56bf1189f2e174be7a10",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/doc-comment/0.3.3/download"],
        strip_prefix = "doc-comment-0.3.3",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.doc-comment-0.3.3.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__either-1.8.0",
        sha256 = "90e5c1c8368803113bf0c9584fc495a58b86dc8a29edbf8fe877d21d9507e797",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/either/1.8.0/download"],
        strip_prefix = "either-1.8.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.either-1.8.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__fastrand-1.8.0",
        sha256 = "a7a407cfaa3385c4ae6b23e84623d48c2798d06e3e6a1878f7f59f17b3f86499",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/fastrand/1.8.0/download"],
        strip_prefix = "fastrand-1.8.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.fastrand-1.8.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__fixedbitset-0.4.2",
        sha256 = "0ce7134b9999ecaf8bcd65542e436736ef32ddca1b3e06094cb6ec5755203b80",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/fixedbitset/0.4.2/download"],
        strip_prefix = "fixedbitset-0.4.2",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.fixedbitset-0.4.2.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__float-cmp-0.9.0",
        sha256 = "98de4bbd547a563b716d8dfa9aad1cb19bfab00f4fa09a6a4ed21dbcf44ce9c4",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/float-cmp/0.9.0/download"],
        strip_prefix = "float-cmp-0.9.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.float-cmp-0.9.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__fnv-1.0.7",
        sha256 = "3f9eec918d3f24069decb9af1554cad7c880e2da24a9afd88aca000531ab82c1",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/fnv/1.0.7/download"],
        strip_prefix = "fnv-1.0.7",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.fnv-1.0.7.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__futures-channel-0.3.23",
        sha256 = "2bfc52cbddcfd745bf1740338492bb0bd83d76c67b445f91c5fb29fae29ecaa1",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/futures-channel/0.3.23/download"],
        strip_prefix = "futures-channel-0.3.23",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.futures-channel-0.3.23.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__futures-core-0.3.23",
        sha256 = "d2acedae88d38235936c3922476b10fced7b2b68136f5e3c03c2d5be348a1115",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/futures-core/0.3.23/download"],
        strip_prefix = "futures-core-0.3.23",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.futures-core-0.3.23.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__futures-macro-0.3.23",
        sha256 = "0db9cce532b0eae2ccf2766ab246f114b56b9cf6d445e00c2549fbc100ca045d",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/futures-macro/0.3.23/download"],
        strip_prefix = "futures-macro-0.3.23",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.futures-macro-0.3.23.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__futures-sink-0.3.23",
        sha256 = "ca0bae1fe9752cf7fd9b0064c674ae63f97b37bc714d745cbde0afb7ec4e6765",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/futures-sink/0.3.23/download"],
        strip_prefix = "futures-sink-0.3.23",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.futures-sink-0.3.23.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__futures-task-0.3.23",
        sha256 = "842fc63b931f4056a24d59de13fb1272134ce261816e063e634ad0c15cdc5306",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/futures-task/0.3.23/download"],
        strip_prefix = "futures-task-0.3.23",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.futures-task-0.3.23.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__futures-util-0.3.23",
        sha256 = "f0828a5471e340229c11c77ca80017937ce3c58cb788a17e5f1c2d5c485a9577",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/futures-util/0.3.23/download"],
        strip_prefix = "futures-util-0.3.23",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.futures-util-0.3.23.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__getrandom-0.2.7",
        sha256 = "4eb1a864a501629691edf6c15a593b7a51eebaa1e8468e9ddc623de7c9b58ec6",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/getrandom/0.2.7/download"],
        strip_prefix = "getrandom-0.2.7",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.getrandom-0.2.7.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__h2-0.3.14",
        sha256 = "5ca32592cf21ac7ccab1825cd87f6c9b3d9022c44d086172ed0966bec8af30be",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/h2/0.3.14/download"],
        strip_prefix = "h2-0.3.14",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.h2-0.3.14.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__hashbrown-0.12.3",
        sha256 = "8a9ee70c43aaf417c914396645a0fa852624801b24ebb7ae78fe8272889ac888",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/hashbrown/0.12.3/download"],
        strip_prefix = "hashbrown-0.12.3",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.hashbrown-0.12.3.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__heck-0.3.3",
        sha256 = "6d621efb26863f0e9924c6ac577e8275e5e6b77455db64ffa6c65c904e9e132c",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/heck/0.3.3/download"],
        strip_prefix = "heck-0.3.3",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.heck-0.3.3.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__heck-0.4.0",
        sha256 = "2540771e65fc8cb83cd6e8a237f70c319bd5c29f78ed1084ba5d50eeac86f7f9",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/heck/0.4.0/download"],
        strip_prefix = "heck-0.4.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.heck-0.4.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__hermit-abi-0.1.19",
        sha256 = "62b467343b94ba476dcb2500d242dadbb39557df889310ac77c5d99100aaac33",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/hermit-abi/0.1.19/download"],
        strip_prefix = "hermit-abi-0.1.19",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.hermit-abi-0.1.19.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__http-0.2.8",
        sha256 = "75f43d41e26995c17e71ee126451dd3941010b0514a81a9d11f3b341debc2399",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/http/0.2.8/download"],
        strip_prefix = "http-0.2.8",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.http-0.2.8.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__http-body-0.4.5",
        sha256 = "d5f38f16d184e36f2408a55281cd658ecbd3ca05cce6d6510a176eca393e26d1",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/http-body/0.4.5/download"],
        strip_prefix = "http-body-0.4.5",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.http-body-0.4.5.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__http-range-header-0.3.0",
        sha256 = "0bfe8eed0a9285ef776bb792479ea3834e8b94e13d615c2f66d03dd50a435a29",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/http-range-header/0.3.0/download"],
        strip_prefix = "http-range-header-0.3.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.http-range-header-0.3.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__httparse-1.7.1",
        sha256 = "496ce29bb5a52785b44e0f7ca2847ae0bb839c9bd28f69acac9b99d461c0c04c",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/httparse/1.7.1/download"],
        strip_prefix = "httparse-1.7.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.httparse-1.7.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__httpdate-1.0.2",
        sha256 = "c4a1e36c821dbe04574f602848a19f742f4fb3c98d40449f11bcad18d6b17421",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/httpdate/1.0.2/download"],
        strip_prefix = "httpdate-1.0.2",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.httpdate-1.0.2.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__hyper-0.14.20",
        sha256 = "02c929dc5c39e335a03c405292728118860721b10190d98c2a0f0efd5baafbac",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/hyper/0.14.20/download"],
        strip_prefix = "hyper-0.14.20",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.hyper-0.14.20.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__hyper-timeout-0.4.1",
        sha256 = "bbb958482e8c7be4bc3cf272a766a2b0bf1a6755e7a6ae777f017a31d11b13b1",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/hyper-timeout/0.4.1/download"],
        strip_prefix = "hyper-timeout-0.4.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.hyper-timeout-0.4.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__indexmap-1.9.1",
        sha256 = "10a35a97730320ffe8e2d410b5d3b69279b98d2c14bdb8b70ea89ecf7888d41e",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/indexmap/1.9.1/download"],
        strip_prefix = "indexmap-1.9.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.indexmap-1.9.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__instant-0.1.12",
        sha256 = "7a5bbe824c507c5da5956355e86a746d82e0e1464f65d862cc5e71da70e94b2c",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/instant/0.1.12/download"],
        strip_prefix = "instant-0.1.12",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.instant-0.1.12.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__itertools-0.10.3",
        sha256 = "a9a9d19fa1e79b6215ff29b9d6880b706147f16e9b1dbb1e4e5947b5b02bc5e3",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/itertools/0.10.3/download"],
        strip_prefix = "itertools-0.10.3",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.itertools-0.10.3.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__itoa-1.0.3",
        sha256 = "6c8af84674fe1f223a982c933a0ee1086ac4d4052aa0fb8060c12c6ad838e754",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/itoa/1.0.3/download"],
        strip_prefix = "itoa-1.0.3",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.itoa-1.0.3.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__js-sys-0.3.59",
        sha256 = "258451ab10b34f8af53416d1fdab72c22e805f0c92a1136d59470ec0b11138b2",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/js-sys/0.3.59/download"],
        strip_prefix = "js-sys-0.3.59",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.js-sys-0.3.59.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__lazy_static-1.4.0",
        sha256 = "e2abad23fbc42b3700f2f279844dc832adb2b2eb069b2df918f455c4e18cc646",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/lazy_static/1.4.0/download"],
        strip_prefix = "lazy_static-1.4.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.lazy_static-1.4.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__libc-0.2.132",
        sha256 = "8371e4e5341c3a96db127eb2465ac681ced4c433e01dd0e938adbef26ba93ba5",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/libc/0.2.132/download"],
        strip_prefix = "libc-0.2.132",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.libc-0.2.132.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__log-0.4.17",
        sha256 = "abb12e687cfb44aa40f41fc3978ef76448f9b6038cad6aef4259d3c095a2382e",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/log/0.4.17/download"],
        strip_prefix = "log-0.4.17",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.log-0.4.17.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__matchit-0.5.0",
        sha256 = "73cbba799671b762df5a175adf59ce145165747bb891505c43d09aefbbf38beb",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/matchit/0.5.0/download"],
        strip_prefix = "matchit-0.5.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.matchit-0.5.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__memchr-2.5.0",
        sha256 = "2dffe52ecf27772e601905b7522cb4ef790d2cc203488bbd0e2fe85fcb74566d",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/memchr/2.5.0/download"],
        strip_prefix = "memchr-2.5.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.memchr-2.5.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__mime-0.3.16",
        sha256 = "2a60c7ce501c71e03a9c9c0d35b861413ae925bd979cc7a4e30d060069aaac8d",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/mime/0.3.16/download"],
        strip_prefix = "mime-0.3.16",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.mime-0.3.16.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__mio-0.8.4",
        sha256 = "57ee1c23c7c63b0c9250c339ffdc69255f110b298b901b9f6c82547b7b87caaf",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/mio/0.8.4/download"],
        strip_prefix = "mio-0.8.4",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.mio-0.8.4.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__multimap-0.8.3",
        sha256 = "e5ce46fe64a9d73be07dcbe690a38ce1b293be448fd8ce1e6c1b8062c9f72c6a",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/multimap/0.8.3/download"],
        strip_prefix = "multimap-0.8.3",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.multimap-0.8.3.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__normalize-line-endings-0.3.0",
        sha256 = "61807f77802ff30975e01f4f071c8ba10c022052f98b3294119f3e615d13e5be",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/normalize-line-endings/0.3.0/download"],
        strip_prefix = "normalize-line-endings-0.3.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.normalize-line-endings-0.3.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__num-traits-0.2.15",
        sha256 = "578ede34cf02f8924ab9447f50c28075b4d3e5b269972345e7e0372b38c6cdcd",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/num-traits/0.2.15/download"],
        strip_prefix = "num-traits-0.2.15",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.num-traits-0.2.15.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__num_cpus-1.13.1",
        sha256 = "19e64526ebdee182341572e50e9ad03965aa510cd94427a4549448f285e957a1",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/num_cpus/1.13.1/download"],
        strip_prefix = "num_cpus-1.13.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.num_cpus-1.13.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__once_cell-1.13.1",
        sha256 = "074864da206b4973b84eb91683020dbefd6a8c3f0f38e054d93954e891935e4e",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/once_cell/1.13.1/download"],
        strip_prefix = "once_cell-1.13.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.once_cell-1.13.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__percent-encoding-2.1.0",
        sha256 = "d4fd5641d01c8f18a23da7b6fe29298ff4b55afcccdf78973b24cf3175fee32e",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/percent-encoding/2.1.0/download"],
        strip_prefix = "percent-encoding-2.1.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.percent-encoding-2.1.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__petgraph-0.6.2",
        sha256 = "e6d5014253a1331579ce62aa67443b4a658c5e7dd03d4bc6d302b94474888143",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/petgraph/0.6.2/download"],
        strip_prefix = "petgraph-0.6.2",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.petgraph-0.6.2.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__pin-project-1.0.12",
        sha256 = "ad29a609b6bcd67fee905812e544992d216af9d755757c05ed2d0e15a74c6ecc",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/pin-project/1.0.12/download"],
        strip_prefix = "pin-project-1.0.12",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.pin-project-1.0.12.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__pin-project-internal-1.0.12",
        sha256 = "069bdb1e05adc7a8990dce9cc75370895fbe4e3d58b9b73bf1aee56359344a55",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/pin-project-internal/1.0.12/download"],
        strip_prefix = "pin-project-internal-1.0.12",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.pin-project-internal-1.0.12.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__pin-project-lite-0.2.9",
        sha256 = "e0a7ae3ac2f1173085d398531c705756c94a4c56843785df85a60c1a0afac116",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/pin-project-lite/0.2.9/download"],
        strip_prefix = "pin-project-lite-0.2.9",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.pin-project-lite-0.2.9.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__pin-utils-0.1.0",
        sha256 = "8b870d8c151b6f2fb93e84a13146138f05d02ed11c7e7c54f8826aaaf7c9f184",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/pin-utils/0.1.0/download"],
        strip_prefix = "pin-utils-0.1.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.pin-utils-0.1.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__ppv-lite86-0.2.16",
        sha256 = "eb9f9e6e233e5c4a35559a617bf40a4ec447db2e84c20b55a6f83167b7e57872",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/ppv-lite86/0.2.16/download"],
        strip_prefix = "ppv-lite86-0.2.16",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.ppv-lite86-0.2.16.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__predicates-2.1.1",
        sha256 = "a5aab5be6e4732b473071984b3164dbbfb7a3674d30ea5ff44410b6bcd960c3c",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/predicates/2.1.1/download"],
        strip_prefix = "predicates-2.1.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.predicates-2.1.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__predicates-core-1.0.3",
        sha256 = "da1c2388b1513e1b605fcec39a95e0a9e8ef088f71443ef37099fa9ae6673fcb",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/predicates-core/1.0.3/download"],
        strip_prefix = "predicates-core-1.0.3",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.predicates-core-1.0.3.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__predicates-tree-1.0.5",
        sha256 = "4d86de6de25020a36c6d3643a86d9a6a9f552107c0559c60ea03551b5e16c032",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/predicates-tree/1.0.5/download"],
        strip_prefix = "predicates-tree-1.0.5",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.predicates-tree-1.0.5.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__prettyplease-0.1.18",
        sha256 = "697ae720ee02011f439e0701db107ffe2916d83f718342d65d7f8bf7b8a5fee9",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/prettyplease/0.1.18/download"],
        strip_prefix = "prettyplease-0.1.18",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.prettyplease-0.1.18.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__proc-macro-error-1.0.4",
        sha256 = "da25490ff9892aab3fcf7c36f08cfb902dd3e71ca0f9f9517bea02a73a5ce38c",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/proc-macro-error/1.0.4/download"],
        strip_prefix = "proc-macro-error-1.0.4",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.proc-macro-error-1.0.4.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__proc-macro-error-attr-1.0.4",
        sha256 = "a1be40180e52ecc98ad80b184934baf3d0d29f979574e439af5a55274b35f869",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/proc-macro-error-attr/1.0.4/download"],
        strip_prefix = "proc-macro-error-attr-1.0.4",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.proc-macro-error-attr-1.0.4.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__proc-macro2-1.0.43",
        sha256 = "0a2ca2c61bc9f3d74d2886294ab7b9853abd9c1ad903a3ac7815c58989bb7bab",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/proc-macro2/1.0.43/download"],
        strip_prefix = "proc-macro2-1.0.43",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.proc-macro2-1.0.43.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__prost-0.11.0",
        sha256 = "399c3c31cdec40583bb68f0b18403400d01ec4289c383aa047560439952c4dd7",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/prost/0.11.0/download"],
        strip_prefix = "prost-0.11.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.prost-0.11.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__prost-build-0.11.1",
        sha256 = "7f835c582e6bd972ba8347313300219fed5bfa52caf175298d860b61ff6069bb",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/prost-build/0.11.1/download"],
        strip_prefix = "prost-build-0.11.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.prost-build-0.11.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__prost-derive-0.11.0",
        sha256 = "7345d5f0e08c0536d7ac7229952590239e77abf0a0100a1b1d890add6ea96364",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/prost-derive/0.11.0/download"],
        strip_prefix = "prost-derive-0.11.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.prost-derive-0.11.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__prost-types-0.11.1",
        sha256 = "4dfaa718ad76a44b3415e6c4d53b17c8f99160dcb3a99b10470fce8ad43f6e3e",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/prost-types/0.11.1/download"],
        strip_prefix = "prost-types-0.11.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.prost-types-0.11.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__quote-1.0.21",
        sha256 = "bbe448f377a7d6961e30f5955f9b8d106c3f5e449d493ee1b125c1d43c2b5179",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/quote/1.0.21/download"],
        strip_prefix = "quote-1.0.21",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.quote-1.0.21.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__rand-0.8.5",
        sha256 = "34af8d1a0e25924bc5b7c43c079c942339d8f0a8b57c39049bef581b46327404",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/rand/0.8.5/download"],
        strip_prefix = "rand-0.8.5",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.rand-0.8.5.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__rand_chacha-0.3.1",
        sha256 = "e6c10a63a0fa32252be49d21e7709d4d4baf8d231c2dbce1eaa8141b9b127d88",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/rand_chacha/0.3.1/download"],
        strip_prefix = "rand_chacha-0.3.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.rand_chacha-0.3.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__rand_core-0.6.3",
        sha256 = "d34f1408f55294453790c48b2f1ebbb1c5b4b7563eb1f418bcfcfdbb06ebb4e7",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/rand_core/0.6.3/download"],
        strip_prefix = "rand_core-0.6.3",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.rand_core-0.6.3.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__redox_syscall-0.2.16",
        sha256 = "fb5a58c1855b4b6819d59012155603f0b22ad30cad752600aadfcb695265519a",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/redox_syscall/0.2.16/download"],
        strip_prefix = "redox_syscall-0.2.16",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.redox_syscall-0.2.16.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__regex-1.6.0",
        sha256 = "4c4eb3267174b8c6c2f654116623910a0fef09c4753f8dd83db29c48a0df988b",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/regex/1.6.0/download"],
        strip_prefix = "regex-1.6.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.regex-1.6.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__regex-automata-0.1.10",
        sha256 = "6c230d73fb8d8c1b9c0b3135c5142a8acee3a0558fb8db5cf1cb65f8d7862132",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/regex-automata/0.1.10/download"],
        strip_prefix = "regex-automata-0.1.10",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.regex-automata-0.1.10.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__regex-syntax-0.6.27",
        sha256 = "a3f87b73ce11b1619a3c6332f45341e0047173771e8b8b73f87bfeefb7b56244",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/regex-syntax/0.6.27/download"],
        strip_prefix = "regex-syntax-0.6.27",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.regex-syntax-0.6.27.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__remove_dir_all-0.5.3",
        sha256 = "3acd125665422973a33ac9d3dd2df85edad0f4ae9b00dafb1a05e43a9f5ef8e7",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/remove_dir_all/0.5.3/download"],
        strip_prefix = "remove_dir_all-0.5.3",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.remove_dir_all-0.5.3.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__ring-0.16.20",
        sha256 = "3053cf52e236a3ed746dfc745aa9cacf1b791d846bdaf412f60a8d7d6e17c8fc",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/ring/0.16.20/download"],
        strip_prefix = "ring-0.16.20",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.ring-0.16.20.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__rustls-0.20.6",
        sha256 = "5aab8ee6c7097ed6057f43c187a62418d0c05a4bd5f18b3571db50ee0f9ce033",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/rustls/0.20.6/download"],
        strip_prefix = "rustls-0.20.6",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.rustls-0.20.6.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__rustls-pemfile-1.0.1",
        sha256 = "0864aeff53f8c05aa08d86e5ef839d3dfcf07aeba2db32f12db0ef716e87bd55",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/rustls-pemfile/1.0.1/download"],
        strip_prefix = "rustls-pemfile-1.0.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.rustls-pemfile-1.0.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__ryu-1.0.11",
        sha256 = "4501abdff3ae82a1c1b477a17252eb69cee9e66eb915c1abaa4f44d873df9f09",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/ryu/1.0.11/download"],
        strip_prefix = "ryu-1.0.11",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.ryu-1.0.11.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__sct-0.7.0",
        sha256 = "d53dcdb7c9f8158937a7981b48accfd39a43af418591a5d008c7b22b5e1b7ca4",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/sct/0.7.0/download"],
        strip_prefix = "sct-0.7.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.sct-0.7.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__serde-1.0.143",
        sha256 = "53e8e5d5b70924f74ff5c6d64d9a5acd91422117c60f48c4e07855238a254553",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/serde/1.0.143/download"],
        strip_prefix = "serde-1.0.143",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.serde-1.0.143.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__serde_derive-1.0.143",
        sha256 = "d3d8e8de557aee63c26b85b947f5e59b690d0454c753f3adeb5cd7835ab88391",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/serde_derive/1.0.143/download"],
        strip_prefix = "serde_derive-1.0.143",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.serde_derive-1.0.143.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__serde_yaml-0.9.9",
        sha256 = "f50845f68d5c693aac7d72a25415ddd21cb8182c04eafe447b73af55a05f9e1b",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/serde_yaml/0.9.9/download"],
        strip_prefix = "serde_yaml-0.9.9",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.serde_yaml-0.9.9.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__slab-0.4.7",
        sha256 = "4614a76b2a8be0058caa9dbbaf66d988527d86d003c11a94fbd335d7661edcef",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/slab/0.4.7/download"],
        strip_prefix = "slab-0.4.7",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.slab-0.4.7.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__socket2-0.4.4",
        sha256 = "66d72b759436ae32898a2af0a14218dbf55efde3feeb170eb623637db85ee1e0",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/socket2/0.4.4/download"],
        strip_prefix = "socket2-0.4.4",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.socket2-0.4.4.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__spin-0.5.2",
        sha256 = "6e63cff320ae2c57904679ba7cb63280a3dc4613885beafb148ee7bf9aa9042d",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/spin/0.5.2/download"],
        strip_prefix = "spin-0.5.2",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.spin-0.5.2.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__strsim-0.8.0",
        sha256 = "8ea5119cdb4c55b55d432abb513a0429384878c15dde60cc77b1c99de1a95a6a",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/strsim/0.8.0/download"],
        strip_prefix = "strsim-0.8.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.strsim-0.8.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__structopt-0.3.26",
        sha256 = "0c6b5c64445ba8094a6ab0c3cd2ad323e07171012d9c98b0b15651daf1787a10",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/structopt/0.3.26/download"],
        strip_prefix = "structopt-0.3.26",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.structopt-0.3.26.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__structopt-derive-0.4.18",
        sha256 = "dcb5ae327f9cc13b68763b5749770cb9e048a99bd9dfdfa58d0cf05d5f64afe0",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/structopt-derive/0.4.18/download"],
        strip_prefix = "structopt-derive-0.4.18",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.structopt-derive-0.4.18.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__syn-1.0.99",
        sha256 = "58dbef6ec655055e20b86b15a8cc6d439cca19b667537ac6a1369572d151ab13",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/syn/1.0.99/download"],
        strip_prefix = "syn-1.0.99",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.syn-1.0.99.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__sync_wrapper-0.1.1",
        sha256 = "20518fe4a4c9acf048008599e464deb21beeae3d3578418951a189c235a7a9a8",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/sync_wrapper/0.1.1/download"],
        strip_prefix = "sync_wrapper-0.1.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.sync_wrapper-0.1.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__tempfile-3.3.0",
        sha256 = "5cdb1ef4eaeeaddc8fbd371e5017057064af0911902ef36b39801f67cc6d79e4",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/tempfile/3.3.0/download"],
        strip_prefix = "tempfile-3.3.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.tempfile-3.3.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__termtree-0.2.4",
        sha256 = "507e9898683b6c43a9aa55b64259b721b52ba226e0f3779137e50ad114a4c90b",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/termtree/0.2.4/download"],
        strip_prefix = "termtree-0.2.4",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.termtree-0.2.4.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__textwrap-0.11.0",
        sha256 = "d326610f408c7a4eb6f51c37c330e496b08506c9457c9d34287ecc38809fb060",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/textwrap/0.11.0/download"],
        strip_prefix = "textwrap-0.11.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.textwrap-0.11.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__tokio-1.20.1",
        sha256 = "7a8325f63a7d4774dd041e363b2409ed1c5cbbd0f867795e661df066b2b0a581",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/tokio/1.20.1/download"],
        strip_prefix = "tokio-1.20.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.tokio-1.20.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__tokio-io-timeout-1.2.0",
        sha256 = "30b74022ada614a1b4834de765f9bb43877f910cc8ce4be40e89042c9223a8bf",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/tokio-io-timeout/1.2.0/download"],
        strip_prefix = "tokio-io-timeout-1.2.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.tokio-io-timeout-1.2.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__tokio-macros-1.8.0",
        sha256 = "9724f9a975fb987ef7a3cd9be0350edcbe130698af5b8f7a631e23d42d052484",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/tokio-macros/1.8.0/download"],
        strip_prefix = "tokio-macros-1.8.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.tokio-macros-1.8.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__tokio-rustls-0.23.4",
        sha256 = "c43ee83903113e03984cb9e5cebe6c04a5116269e900e3ddba8f068a62adda59",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/tokio-rustls/0.23.4/download"],
        strip_prefix = "tokio-rustls-0.23.4",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.tokio-rustls-0.23.4.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__tokio-stream-0.1.9",
        sha256 = "df54d54117d6fdc4e4fea40fe1e4e566b3505700e148a6827e59b34b0d2600d9",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/tokio-stream/0.1.9/download"],
        strip_prefix = "tokio-stream-0.1.9",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.tokio-stream-0.1.9.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__tokio-util-0.7.3",
        sha256 = "cc463cd8deddc3770d20f9852143d50bf6094e640b485cb2e189a2099085ff45",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/tokio-util/0.7.3/download"],
        strip_prefix = "tokio-util-0.7.3",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.tokio-util-0.7.3.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__tonic-0.8.0",
        sha256 = "498f271adc46acce75d66f639e4d35b31b2394c295c82496727dafa16d465dd2",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/tonic/0.8.0/download"],
        strip_prefix = "tonic-0.8.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.tonic-0.8.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__tonic-build-0.8.0",
        sha256 = "2fbcd2800e34e743b9ae795867d5f77b535d3a3be69fd731e39145719752df8c",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/tonic-build/0.8.0/download"],
        strip_prefix = "tonic-build-0.8.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.tonic-build-0.8.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__tonic-health-0.7.0",
        sha256 = "1ec5901d5260e1b7f6b5c76bfbd0b5f581cd861554b4b76597ced3cd65543561",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/tonic-health/0.7.0/download"],
        strip_prefix = "tonic-health-0.7.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.tonic-health-0.7.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__tower-0.4.13",
        sha256 = "b8fa9be0de6cf49e536ce1851f987bd21a43b771b09473c3549a6c853db37c1c",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/tower/0.4.13/download"],
        strip_prefix = "tower-0.4.13",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.tower-0.4.13.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__tower-http-0.3.4",
        sha256 = "3c530c8675c1dbf98facee631536fa116b5fb6382d7dd6dc1b118d970eafe3ba",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/tower-http/0.3.4/download"],
        strip_prefix = "tower-http-0.3.4",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.tower-http-0.3.4.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__tower-layer-0.3.1",
        sha256 = "343bc9466d3fe6b0f960ef45960509f84480bf4fd96f92901afe7ff3df9d3a62",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/tower-layer/0.3.1/download"],
        strip_prefix = "tower-layer-0.3.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.tower-layer-0.3.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__tower-service-0.3.2",
        sha256 = "b6bc1c9ce2b5135ac7f93c72918fc37feb872bdc6a5533a8b85eb4b86bfdae52",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/tower-service/0.3.2/download"],
        strip_prefix = "tower-service-0.3.2",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.tower-service-0.3.2.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__tracing-0.1.36",
        sha256 = "2fce9567bd60a67d08a16488756721ba392f24f29006402881e43b19aac64307",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/tracing/0.1.36/download"],
        strip_prefix = "tracing-0.1.36",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.tracing-0.1.36.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__tracing-attributes-0.1.22",
        sha256 = "11c75893af559bc8e10716548bdef5cb2b983f8e637db9d0e15126b61b484ee2",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/tracing-attributes/0.1.22/download"],
        strip_prefix = "tracing-attributes-0.1.22",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.tracing-attributes-0.1.22.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__tracing-core-0.1.29",
        sha256 = "5aeea4303076558a00714b823f9ad67d58a3bbda1df83d8827d21193156e22f7",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/tracing-core/0.1.29/download"],
        strip_prefix = "tracing-core-0.1.29",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.tracing-core-0.1.29.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__tracing-futures-0.2.5",
        sha256 = "97d095ae15e245a057c8e8451bab9b3ee1e1f68e9ba2b4fbc18d0ac5237835f2",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/tracing-futures/0.2.5/download"],
        strip_prefix = "tracing-futures-0.2.5",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.tracing-futures-0.2.5.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__try-lock-0.2.3",
        sha256 = "59547bce71d9c38b83d9c0e92b6066c4253371f15005def0c30d9657f50c7642",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/try-lock/0.2.3/download"],
        strip_prefix = "try-lock-0.2.3",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.try-lock-0.2.3.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__unicode-ident-1.0.3",
        sha256 = "c4f5b37a154999a8f3f98cc23a628d850e154479cd94decf3414696e12e31aaf",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/unicode-ident/1.0.3/download"],
        strip_prefix = "unicode-ident-1.0.3",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.unicode-ident-1.0.3.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__unicode-segmentation-1.9.0",
        sha256 = "7e8820f5d777f6224dc4be3632222971ac30164d4a258d595640799554ebfd99",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/unicode-segmentation/1.9.0/download"],
        strip_prefix = "unicode-segmentation-1.9.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.unicode-segmentation-1.9.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__unicode-width-0.1.9",
        sha256 = "3ed742d4ea2bd1176e236172c8429aaf54486e7ac098db29ffe6529e0ce50973",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/unicode-width/0.1.9/download"],
        strip_prefix = "unicode-width-0.1.9",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.unicode-width-0.1.9.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__unsafe-libyaml-0.2.2",
        sha256 = "931179334a56395bcf64ba5e0ff56781381c1a5832178280c7d7f91d1679aeb0",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/unsafe-libyaml/0.2.2/download"],
        strip_prefix = "unsafe-libyaml-0.2.2",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.unsafe-libyaml-0.2.2.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__untrusted-0.7.1",
        sha256 = "a156c684c91ea7d62626509bce3cb4e1d9ed5c4d978f7b4352658f96a4c26b4a",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/untrusted/0.7.1/download"],
        strip_prefix = "untrusted-0.7.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.untrusted-0.7.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__vec_map-0.8.2",
        sha256 = "f1bddf1187be692e79c5ffeab891132dfb0f236ed36a43c7ed39f1165ee20191",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/vec_map/0.8.2/download"],
        strip_prefix = "vec_map-0.8.2",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.vec_map-0.8.2.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__version_check-0.9.4",
        sha256 = "49874b5167b65d7193b8aba1567f5c7d93d001cafc34600cee003eda787e483f",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/version_check/0.9.4/download"],
        strip_prefix = "version_check-0.9.4",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.version_check-0.9.4.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__wait-timeout-0.2.0",
        sha256 = "9f200f5b12eb75f8c1ed65abd4b2db8a6e1b138a20de009dacee265a2498f3f6",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/wait-timeout/0.2.0/download"],
        strip_prefix = "wait-timeout-0.2.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.wait-timeout-0.2.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__want-0.3.0",
        sha256 = "1ce8a968cb1cd110d136ff8b819a556d6fb6d919363c61534f6860c7eb172ba0",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/want/0.3.0/download"],
        strip_prefix = "want-0.3.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.want-0.3.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__wasi-0.11.0-wasi-snapshot-preview1",
        sha256 = "9c8d87e72b64a3b4db28d11ce29237c246188f4f51057d65a7eab63b7987e423",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/wasi/0.11.0+wasi-snapshot-preview1/download"],
        strip_prefix = "wasi-0.11.0+wasi-snapshot-preview1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.wasi-0.11.0+wasi-snapshot-preview1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__wasm-bindgen-0.2.82",
        sha256 = "fc7652e3f6c4706c8d9cd54832c4a4ccb9b5336e2c3bd154d5cccfbf1c1f5f7d",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/wasm-bindgen/0.2.82/download"],
        strip_prefix = "wasm-bindgen-0.2.82",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.wasm-bindgen-0.2.82.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__wasm-bindgen-backend-0.2.82",
        sha256 = "662cd44805586bd52971b9586b1df85cdbbd9112e4ef4d8f41559c334dc6ac3f",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/wasm-bindgen-backend/0.2.82/download"],
        strip_prefix = "wasm-bindgen-backend-0.2.82",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.wasm-bindgen-backend-0.2.82.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__wasm-bindgen-macro-0.2.82",
        sha256 = "b260f13d3012071dfb1512849c033b1925038373aea48ced3012c09df952c602",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/wasm-bindgen-macro/0.2.82/download"],
        strip_prefix = "wasm-bindgen-macro-0.2.82",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.wasm-bindgen-macro-0.2.82.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__wasm-bindgen-macro-support-0.2.82",
        sha256 = "5be8e654bdd9b79216c2929ab90721aa82faf65c48cdf08bdc4e7f51357b80da",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/wasm-bindgen-macro-support/0.2.82/download"],
        strip_prefix = "wasm-bindgen-macro-support-0.2.82",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.wasm-bindgen-macro-support-0.2.82.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__wasm-bindgen-shared-0.2.82",
        sha256 = "6598dd0bd3c7d51095ff6531a5b23e02acdc81804e30d8f07afb77b7215a140a",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/wasm-bindgen-shared/0.2.82/download"],
        strip_prefix = "wasm-bindgen-shared-0.2.82",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.wasm-bindgen-shared-0.2.82.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__web-sys-0.3.59",
        sha256 = "ed055ab27f941423197eb86b2035720b1a3ce40504df082cac2ecc6ed73335a1",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/web-sys/0.3.59/download"],
        strip_prefix = "web-sys-0.3.59",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.web-sys-0.3.59.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__webpki-0.22.0",
        sha256 = "f095d78192e208183081cc07bc5515ef55216397af48b873e5edcd72637fa1bd",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/webpki/0.22.0/download"],
        strip_prefix = "webpki-0.22.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.webpki-0.22.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__which-4.2.5",
        sha256 = "5c4fb54e6113b6a8772ee41c3404fb0301ac79604489467e0a9ce1f3e97c24ae",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/which/4.2.5/download"],
        strip_prefix = "which-4.2.5",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.which-4.2.5.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__winapi-0.3.9",
        sha256 = "5c839a674fcd7a98952e593242ea400abe93992746761e38641405d28b00f419",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/winapi/0.3.9/download"],
        strip_prefix = "winapi-0.3.9",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.winapi-0.3.9.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__winapi-i686-pc-windows-gnu-0.4.0",
        sha256 = "ac3b87c63620426dd9b991e5ce0329eff545bccbbb34f3be09ff6fb6ab51b7b6",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/winapi-i686-pc-windows-gnu/0.4.0/download"],
        strip_prefix = "winapi-i686-pc-windows-gnu-0.4.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.winapi-i686-pc-windows-gnu-0.4.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__winapi-x86_64-pc-windows-gnu-0.4.0",
        sha256 = "712e227841d057c1ee1cd2fb22fa7e5a5461ae8e48fa2ca79ec42cfc1931183f",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/winapi-x86_64-pc-windows-gnu/0.4.0/download"],
        strip_prefix = "winapi-x86_64-pc-windows-gnu-0.4.0",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.winapi-x86_64-pc-windows-gnu-0.4.0.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__windows-sys-0.36.1",
        sha256 = "ea04155a16a59f9eab786fe12a4a450e75cdb175f9e0d80da1e17db09f55b8d2",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/windows-sys/0.36.1/download"],
        strip_prefix = "windows-sys-0.36.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.windows-sys-0.36.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__windows_aarch64_msvc-0.36.1",
        sha256 = "9bb8c3fd39ade2d67e9874ac4f3db21f0d710bee00fe7cab16949ec184eeaa47",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/windows_aarch64_msvc/0.36.1/download"],
        strip_prefix = "windows_aarch64_msvc-0.36.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.windows_aarch64_msvc-0.36.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__windows_i686_gnu-0.36.1",
        sha256 = "180e6ccf01daf4c426b846dfc66db1fc518f074baa793aa7d9b9aaeffad6a3b6",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/windows_i686_gnu/0.36.1/download"],
        strip_prefix = "windows_i686_gnu-0.36.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.windows_i686_gnu-0.36.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__windows_i686_msvc-0.36.1",
        sha256 = "e2e7917148b2812d1eeafaeb22a97e4813dfa60a3f8f78ebe204bcc88f12f024",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/windows_i686_msvc/0.36.1/download"],
        strip_prefix = "windows_i686_msvc-0.36.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.windows_i686_msvc-0.36.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__windows_x86_64_gnu-0.36.1",
        sha256 = "4dcd171b8776c41b97521e5da127a2d86ad280114807d0b2ab1e462bc764d9e1",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/windows_x86_64_gnu/0.36.1/download"],
        strip_prefix = "windows_x86_64_gnu-0.36.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.windows_x86_64_gnu-0.36.1.bazel"),
    )

    maybe(
        http_archive,
        name = "crates_vendor__windows_x86_64_msvc-0.36.1",
        sha256 = "c811ca4a8c853ef420abd8592ba53ddbbac90410fab6903b3e79972a631f7680",
        type = "tar.gz",
        urls = ["https://crates.io/api/v1/crates/windows_x86_64_msvc/0.36.1/download"],
        strip_prefix = "windows_x86_64_msvc-0.36.1",
        build_file = Label("@paypizza_grpc_health_check//crates:BUILD.windows_x86_64_msvc-0.36.1.bazel"),
    )
